[project]
name = "url-lookup-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
commit = [
    "pre-commit>=4.5.1",
]
dev = [
    "ruff>=0.14.10",
]
